### ISSUE TITLE
I tried it 

### ISSUE THREAD

**Issue by SPIRY-RO** [mahiso/poloniexlendingbot#1]
```
  File "lendingbot.py", line 82, in <module>
    Lending.cancel_all()
  File "/root/bitfinexlending/modules/Lending.py", line 176, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/root/bitfinexlending/modules/Bitfinex.py", line 76, in return_open_loan_offers
    resp = Bitfinex2Poloniex.convertOpenLoanOffers(bfxResp)
  File "/root/bitfinexlending/modules/Bitfinex2Poloniex.py", line 26, in convertOpenLoanOffers
    if offer['currency'] not in plx_offers:
NameError: global name 'plx_offers' is not defined


```

I have this issue when I start it .....

**Comment by mahiso** [comment]
Bitfinex lending is not ready yet. Please use master branch or upstream master to lend on Poloniex.

I will close this issue when Bitfinex lending is ready to go.

**Comment by SPIRY-RO** [comment]
I am using on production the Poloniex. And I wish so bad for the Bitfinex edition. 
My live prod: [url removed]

**Comment by SPIRY-RO** [comment]
You have any ETA. Damn I am so pissed, I need to learn more Python.

**Comment by mahiso** [comment]
Sorry, no ETA, it's a spare time project.

**Comment by SPIRY-RO** [comment]
Not even if I would tip you for a fasten process? :) We can take it in private my skype is spirymedia just like that.

**Comment by SPIRY-RO** [comment]
Awesome. I'll just test it out and see how it goes.

**Comment by mahiso** [comment]
Give me one or two days. And you will get a beta.

**Comment by SPIRY-RO** [comment]
Thanks a lot man. Just read you message now. Can't wait for it.

**Comment by SPIRY-RO** [comment]
Also leave me an BTC or ETH address.

**Comment by mahiso** [comment]
@SpiryMedia Ready to test!

Regarding the "nonce", please create a new API key on Bitfinex. The nonce in one request must always be greater than the nonce in last request. Therefore it is not possible to use one API key in more than one application.

The bot prints out mass of debug messages to console. Its only to test/debug it. I will remove it in final release.

Please test, test , test :-) I like to get your feedback! All kinds of feedback!

Sure, donations are welcome. Thanks for that!! My btc address is: 1HnPJoUDyK87aLH8dAeVsSANSn6XvurWpq

**Comment by SPIRY-RO** [comment]
Just read the news. I'll test it now, also donation sent.

**Comment by SPIRY-RO** [comment]
I've resent an donation for your effort as exactly in the moment of the posting I've been hacked of 1.33 BTC and I've gave you something that I had a left over on an exchange , etc. Anyway now all is good. The code is working perfect! 

Now I'll try the impossible. To unite the logs of both into a single page as informational.

**Comment by mahiso** [comment]
Thanks for donation and testing. Nice to hear that it works for you. I submitted a PR to upstream.
